package com.author.toan;

public enum STATE {
    MAIN,
    REGISTRATION,
    INPUT_PHONE_NUMBER,
    INPUT_OTP,
    INPUT_PASSWORD,
    LOGIN,
    FORGOT_PASSWORD,
    CHAT,
    VIEW_ACCOUNT,
    VIEW_PRIVACY,
    VIEW_PROFILE,
    VIEW_TIME_LINE,
    VIEW_FRIEND,
    VIEW_GROUP,
    VIEW_MESSAGE,
    CHANGE_PASSWORD,
    EDIT_PROFILE,
    UPLOAD_IMAGE
}
